name: Fetch

on:
  workflow_dispatch:
  schedule:
    # 表达式生成 https://crontab.guru/
    - cron: '58 * * * *'
  push:
    paths:
      - 'sources.list'
      - 'config.yml'
      - '.github/workflows/**'
      - '**.py'
      - 'snippets/_*'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd freevm && pip install -r requirements.txt
      
    - name: Run Python
      run: print("main.py")
    
    - name: 执行任务
      run: cd freevm && python ./fetch.py
      env:              
        wxid: ${{ secrets.wxid }}
        wxsecret: ${{ secrets.wxsecret }}
        TZ: Asia/Shanghai
        
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add freevm/list*
        git add freevm/snippets/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 抓取节点"
    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: main
